name: EC2-CI/CD


on: 
    push:
        branches: 
            - main
    pull_request: 
        branches:
          - main

jobs: 
    builds: 
        runs-on : ubuntu-latest


        steps:
            - name: Checkout
              uses: actions/checkout@v3


            - name: docker build
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}